let parsed=null, csvs={};
const starCols=['Name','Description','Luminosity (Solar)','Solar Temperature','System Age (bn years)','Spectral Class','Star Type','System Type','Survey Status'];
const planetCols=['Name','Parent Star','Description','Planetary Description','Classification','Planet Distance from Star (AU)','Distance from Star','Mass','Raw Mass','Day Length','Atmospheric Composition','Atmospheric Pressure','Atmosphere Density Factor','Life Sign','Fluid State','Tectonic Status','Star Luminosity (Solar)','System Age (bn years)','Satellite Distances','Strategic Resources'];
const moonCols=['Name','Parent Planet','Lunar Description','Calculated Orbital Distance','Orbit Period','Rotational Period','Atmosphere','Life Sign','Satellite Class','Tidal Locking Prediction','Strategic Value'];
function spectral(t){if(t>=30000)return'O';if(t>=10000)return'B';if(t>=7500)return'A';if(t>=6000)return'F';if(t>=5200)return'G';if(t>=3700)return'K';return'M'}
function life(v){return v>=2?'Complex Life':v===1?'Microbial Life':'No Known Life'}
function geo(v){return v>=3?'Extreme Geologic Activity':v===2?'Active':v===1?'Low Activity':'Geologically Dead'}
function atmosphere(o){return !o.atmobasegas||o.atmobasegas==='none'?'None':`${o.atmobasegas}`}
function pclass(p){if(p.gas>.5)return'Gas Giant';if(p.ice>.45)return'Ice World';if(p.mass>=2)return'Super-Earth';if(p.mass<.05)return'Dwarf Planet';return'Terrestrial Planet'}
function mclass(m){if(m.ice>.45)return'Icy Moon';if(m.rock>.6)return'Rocky Moon';return'Mixed Moon'}
function descStar(s){return `${s.name} is a ${spectral(s.temp)}-class generated star with ${Number(s.luma).toFixed(3)} solar luminosity and ${s.planets?.length||0} recorded planets.`}
function descPlanet(p,s){return `${p.name} orbits ${s.name} at ${Number(p.distanceFromParent).toFixed(3)} AU. It is classified as ${pclass(p).toLowerCase()}, with ${life(p.life).toLowerCase()} and ${geo(p.geoactive).toLowerCase()}.`}
function descMoon(m,p){return `${m.name} is a ${mclass(m).toLowerCase()} orbiting ${p.name}. It is ${m.tidalLock?'tidally locked':'not confirmed tidally locked'} and has ${life(m.life).toLowerCase()}.`}
function parseText(txt){let cleaned=txt.trim(); let obj=JSON.parse(cleaned); return obj}
function rows(system){let star={}; star['Name']=system.name||'Unnamed Star'; star['Description']=descStar(system); star['Luminosity (Solar)']=system.luma; star['Solar Temperature']=system.temp; star['System Age (bn years)']=(system.age||0)/1000; star['Spectral Class']=spectral(system.temp); star['Star Type']=system.WD?'White Dwarf':'Main Sequence Star'; star['System Type']=system.isPrimary?'Primary Star System':'Star System'; star['Survey Status']='Generated';
 let planets=[],moons=[]; (system.planets||[]).forEach(p=>{let pr={}; pr['Name']=p.name; pr['Parent Star']=system.name; pr['Description']=descPlanet(p,system); pr['Planetary Description']=pr['Description']; pr['Classification']=pclass(p); pr['Planet Distance from Star (AU)']=p.distanceFromParent; pr['Distance from Star']=`${Number(p.distanceFromParent).toFixed(3)} AU`; pr['Mass']=p.mass; pr['Raw Mass']=p.mass; pr['Day Length']=`${Number(p.dayCycle||0).toFixed(2)} days`; pr['Atmospheric Composition']=atmosphere(p); pr['Atmospheric Pressure']=p.atmothickness; pr['Atmosphere Density Factor']=p.atmothickness; pr['Life Sign']=life(p.life); pr['Fluid State']=p.liquid==='0'?'Surface Liquid Present':'No Stable Surface Liquid'; pr['Tectonic Status']=geo(p.geoactive); pr['Star Luminosity (Solar)']=system.luma; pr['System Age (bn years)']=(system.age||0)/1000; pr['Satellite Distances']=(p.moons||[]).map(m=>`${m.name}: ${m.distanceFromParent} AU`).join('; '); pr['Strategic Resources']='To be assessed'; planets.push(pr);
  (p.moons||[]).forEach(m=>{let mr={}; mr['Name']=m.name; mr['Parent Planet']=p.name; mr['Lunar Description']=descMoon(m,p); mr['Calculated Orbital Distance']=m.distanceFromParent; mr['Orbit Period']=`${Number(m.dayCycle||0).toFixed(2)} days`; mr['Rotational Period']=`${Number(m.dayCycle||0).toFixed(2)} days`; mr['Atmosphere']=atmosphere(m); mr['Life Sign']=life(m.life); mr['Satellite Class']=mclass(m); mr['Tidal Locking Prediction']=m.tidalLock?'Tidally Locked':'Independent Rotation'; mr['Strategic Value']=m.life?'Astrobiological Interest':'Low'; moons.push(mr)});
 }); return {stars:[star],planets,moons}}
function csv(cols,rs){let esc=v=>`"${String(v??'').replaceAll('"','""')}"`; return [cols.join(','),...rs.map(r=>cols.map(c=>esc(r[c])).join(','))].join('\n')}
function table(title, cols, rs){return `<h2>${title}</h2><table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rs.slice(0,20).map(r=>`<tr>${cols.map(c=>`<td>${r[c]??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
async function getInput(){const f=document.getElementById('file').files[0]; if(f)return await f.text(); return document.getElementById('paste').value}
document.getElementById('parse').onclick=async()=>{try{parsed=parseText(await getInput()); let r=rows(parsed); csvs.stars=csv(starCols,r.stars); csvs.planets=csv(planetCols,r.planets); csvs.moons=csv(moonCols,r.moons); document.getElementById('summary').className='card'; document.getElementById('summary').innerHTML=`<h2>Preview</h2><div class="grid"><div class="metric"><b>${parsed.name}</b>Star</div><div class="metric"><b>${r.planets.length}</b>Planets</div><div class="metric"><b>${r.moons.length}</b>Moons</div><div class="metric"><b>${spectral(parsed.temp)}</b>Spectral Class</div></div><p class="warn card">Pure GitHub Pages cannot safely perform direct Notion API imports. Use the included GitHub Actions workflow for automatic import, or download CSVs here.</p>`; document.getElementById('tables').className=''; document.getElementById('preview').innerHTML=table('Stars CSV Preview',starCols,r.stars)+table('Planets CSV Preview',planetCols,r.planets)+table('Moons CSV Preview',moonCols,r.moons)}catch(e){alert('Could not parse file/text: '+e.message)}};
function dl(name,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=name;a.click()}
downloadStars.onclick=()=>dl('stars_import.csv',csvs.stars);downloadPlanets.onclick=()=>dl('planets_import.csv',csvs.planets);downloadMoons.onclick=()=>dl('moons_import.csv',csvs.moons);
